services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-quality-label-service
    command: ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - "./src:/src"
    ports:
      - "8000:8000"
